import {zipFiles} from './zip.js';
import {escapeHtml as esc} from './logic.js';
import {parse,PROBLEMS,taskCount,canCheck,buildFolderCapture,validateCapture} from './capture-logic.js';
const $=id=>document.getElementById(id);
export class CaptureUI {
 constructor({sync,getRecord,toast}){Object.assign(this,{sync,getRecord,toast});this.urls=new Map();this.index=0;this.agent=null;this.agentState=null;this.previewUrl=null;this.loaded=false;this.activeRequest=0;
  document.addEventListener('click',e=>{const b=e.target.closest('[data-capture]');if(b)this.action(b.dataset.capture,b);});
  $('capture-folder').addEventListener('change',e=>this.importFolder([...e.target.files]).catch(err=>this.toast(err.message)).finally(()=>{e.target.value='';}));
  $('problem-form').addEventListener('submit',e=>{e.preventDefault();const id=this.problemTask;this.sync.edit(id,{problem:JSON.stringify({reason:$('problem-reason').value,comment:$('problem-comment').value,step:this.index+1,time:new Date().toISOString()}),status:'needs_review'});$('problem-dialog').close();this.toast('Передано на проверку');});
  $('agent-form').addEventListener('submit',e=>{e.preventDefault();this.connectAgent().catch(err=>{$('agent-error').textContent=err.message;});});
  document.addEventListener('keydown',e=>{if(!$('review-dialog').open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();this.reviewNext(1);}if(e.key==='ArrowLeft'){e.preventDefault();this.reviewNext(-1);}if(e.key==='Enter'){e.preventDefault();this.decide('accepted');}if(e.key.toLowerCase()==='r'||e.key.toLowerCase()==='к'){e.preventDefault();this.decide('rejected');}});
  setInterval(()=>this.pollAgent(),1000);
 }
 mount(task){this.task=task;const r=this.getRecord(task.id),c=parse(r.capture),review=parse(r.review),count=taskCount(task),accepted=c.frames?.filter(f=>review.sessionId===c.sessionId&&review.decisions?.[f.id]?.decision==='accepted').length??0;
  const problem=parse(r.problem);const panel=$('capture-panel');if(!panel)return;
  panel.innerHTML=`<section class="capture-panel"><div class="section-header"><h2>Сбор и проверка</h2><span>${task.mode==='isolated'?'12 ракурсов через 30°':'28 кадров за проезд'}</span></div><p class="capture-instruction">${task.mode==='isolated'?'Сверьте SKU. Поворачивайте упаковку по подсказкам, убирайте руку и выдерживайте паузу. Широкие стороны разрешены.':'Соберите выкладку по плану, одинаково поверните три экземпляра каждого SKU. После подготовки запускается полный проезд туда и обратно.'}</p><div class="capture-stats"><span>Записано <b>${c.frames?.length??0}/${count}</b></span><span>Принято <b>${accepted}/${count}</b></span><span>${c.sessionId?esc(c.sessionId):'Нет подтверждённых файлов'}</span></div><div class="capture-actions"><button class="button primary" data-capture="review" ${!c.frames?.length?'disabled':''}>Проверить кадры</button><button class="button" data-capture="folder">Добавить папку съёмки</button><button class="button" data-capture="export" ${!c.frames?.length?'disabled':''}>Скачать актуальные кадры</button><button class="button" data-capture="agent">Камера и сбор</button><button class="button" data-capture="problem">Сообщить о проблеме</button><button class="button quiet" data-capture="history">История пересъёмок</button></div>${problem.reason?`<p class="problem-note">Нужна проверка: ${esc(problem.reason)} · ${esc(problem.comment??'')}</p>`:''}<div id="upload-state" role="status"></div><p class="muted small">«Записано» подтверждается файлами. «Проверено» — после принятия всех кадров. Оригиналы кадров доступны команде; видео остаётся на компьютере сбора.</p></section>`;
 }
 async action(name,b){try{
  if(name==='folder'){if(!this.sync.connected)throw new Error('Сначала подключите общий журнал');$('capture-folder').click();}
  if(name==='review'){this.reviewTask=this.task;this.index=0;this.historyCapture=null;$('review-dialog').showModal();await this.renderReview();}
  if(name==='next')this.reviewNext(1);if(name==='previous')this.reviewNext(-1);
  if(name==='accept')await this.decide('accepted');if(name==='reject')await this.decide('rejected');
  if(name==='check')await this.markChecked();if(name==='reshoot')this.reshoot();
  if(name==='problem'){this.problemTask=this.task.id;$('problem-reason').innerHTML=PROBLEMS.map(p=>`<option>${esc(p)}</option>`).join('');$('problem-comment').value='';$('problem-dialog').showModal();}
  if(name==='agent'){$('agent-dialog').showModal();this.renderAgent();}
  if(name==='disconnect-agent'){this.agent=null;this.agentState=null;this.renderAgent();}
  if(name==='agent-start'){await this.agentCommand('/local/start',{sceneId:this.task.id,operator:$('operator-name').value,requestId:crypto.randomUUID()});this.sync.edit(this.task.id,{status:'collecting',operator:$('operator-name').value,session:this.agentState.sessionId??''});}
  if(name==='agent-save')await this.agentCommand('/local/save',{requestId:crypto.randomUUID()});
  if(name==='agent-reshoot')await this.agentCommand('/local/reshoot',{step:Number($('agent-step').value),requestId:crypto.randomUUID()});
  if(name==='agent-stop')await this.agentCommand('/local/stop',{requestId:crypto.randomUUID()});
  if(name==='agent-import')await this.importAgent();
  if(name==='history')await this.history();if(name==='export')await this.exportFrames();
 }catch(e){this.toast(e.message);}}
 capture(){return this.historyCapture??parse(this.getRecord(this.reviewTask.id).capture);}
 async image(key){if(this.urls.has(key))return this.urls.get(key);const res=await this.sync.api('/api/image?key='+encodeURIComponent(key));const url=URL.createObjectURL(await res.blob());this.urls.set(key,url);if(this.urls.size>60){const first=this.urls.keys().next().value;URL.revokeObjectURL(this.urls.get(first));this.urls.delete(first);}return url;}
 async renderReview(){const c=this.capture(),f=c.frames?.[this.index];if(!f)return;const r=parse(this.getRecord(this.reviewTask.id).review),d=r.sessionId===c.sessionId?r.decisions?.[f.id]:null;this.loaded=false;const request=++this.activeRequest;
  $('review-title').textContent=`${this.reviewTask.mode==='isolated'?this.reviewTask.name:this.reviewTask.id} · кадр ${this.index+1}/${c.frames.length}`;
  $('review-position').textContent=`Шаг ${f.step} · ${f.yaw??'—'}° · ${d?.decision==='accepted'?'Принят':d?.decision==='rejected'?'Отклонён':'Не проверен'}${this.historyCapture?' · история, только просмотр':''}`;
  $('review-image').removeAttribute('src');$('review-load').textContent='Загрузка оригинала…';$('review-image').alt='Кадр шага '+f.step;
  $('review-strip').innerHTML=c.frames.map((x,i)=>`<button class="frame-number ${i===this.index?'active':''} ${r.sessionId===c.sessionId?r.decisions?.[x.id]?.decision??'':''}" data-frame-index="${i}" aria-label="Кадр ${i+1}"><img data-thumb-key="${esc(x.imageKey)}" alt=""><span>${i+1}</span></button>`).join('');
  for(const img of $('review-strip').querySelectorAll('[data-thumb-key]'))this.image(img.dataset.thumbKey).then(url=>{if(img.isConnected)img.src=url;}).catch(()=>{});
  for(const b of $('review-strip').querySelectorAll('[data-frame-index]'))b.onclick=()=>{this.index=Number(b.dataset.frameIndex);this.renderReview();};
  $('review-check').disabled=!canCheck(c,r,taskCount(this.reviewTask))||!!this.historyCapture;
  $('review-reshoot').textContent=this.reviewTask.mode==='isolated'?'Переснять отклонённые ракурсы':'Повторить весь проезд полки';
  $('review-controls').querySelectorAll('[data-capture="accept"],[data-capture="reject"]').forEach(b=>b.disabled=true);
  try{const src=await this.image(f.imageKey);if(request!==this.activeRequest)return;$('review-image').onload=()=>{this.loaded=true;$('review-load').textContent='';$('review-controls').querySelectorAll('[data-capture="accept"],[data-capture="reject"]').forEach(b=>b.disabled=!!this.historyCapture);};$('review-image').onerror=()=>{$('review-load').textContent='Изображение не удалось открыть';this.loaded=false;};$('review-image').src=src;}catch(e){$('review-load').textContent=e.message;}
 }
 reviewNext(offset){const n=this.capture().frames?.length??0;this.index=Math.max(0,Math.min(n-1,this.index+offset));this.renderReview();}
 async decide(decision){if(!this.loaded||this.historyCapture)return;const c=this.capture(),f=c.frames[this.index],old=parse(this.getRecord(this.reviewTask.id).review);const review=old.sessionId===c.sessionId?old:{sessionId:c.sessionId,decisions:{}};review.decisions[f.id]={decision,imageKey:f.imageKey,reason:decision==='rejected'?$('reject-reason').value:'',reviewer:$('reviewer-name').value||'Не указан',at:new Date().toISOString()};this.sync.edit(this.reviewTask.id,{review:JSON.stringify(review),...(decision==='rejected'?{status:'needs_review'}:{})});if(this.index<c.frames.length-1)this.index++;await this.renderReview();}
 async markChecked(){const c=this.capture(),r=parse(this.getRecord(this.reviewTask.id).review);if(!canCheck(c,r,taskCount(this.reviewTask)))throw new Error('Примите каждый кадр');await this.sync.sync();if(Object.keys(this.sync.conflicts).length||!this.sync.connected)throw new Error('Сначала дождитесь синхронизации проверки');this.sync.edit(this.reviewTask.id,{status:'checked'});await this.sync.sync();if(this.sync.pending[this.reviewTask.id+':status'])throw new Error('Подтверждение пока не сохранено на сервере');this.toast('Задание проверено');$('review-dialog').close();}
 reshoot(){if(this.historyCapture)return;const c=this.capture(),r=parse(this.getRecord(this.reviewTask.id).review);const rejected=c.frames.filter(f=>r.decisions?.[f.id]?.decision==='rejected').map(f=>f.step);this.sync.edit(this.reviewTask.id,{status:'reshoot',problem:JSON.stringify({reason:this.reviewTask.mode==='isolated'?'Переснять ракурсы':'Повторить весь проезд',steps:rejected.length?rejected:[c.frames[this.index].step],sessionId:c.sessionId,time:new Date().toISOString()})});this.toast(this.reviewTask.mode==='isolated'?'Ракурсы отмечены для пересъёмки':'Нужен новый полный проезд полки');$('review-dialog').close();}
 async upload(task,rows,metadata){if(!this.sync.connected)throw new Error('Нет подключения к общему журналу');const frames=[];
  for(let i=0;i<rows.length;i++){const row=rows[i],type=row.file.type||(/\.png$/i.test(row.file.name)?'image/png':'image/jpeg');if(row.file.size>2000000)throw new Error('Кадр больше 2 МБ: '+row.file.name);$('upload-state').textContent=`Запись оригиналов: ${i+1}/${rows.length}`;
   const bytes=await row.file.arrayBuffer(),sha=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');const res=await this.sync.api('/api/image',{method:'PUT',headers:{'Content-Type':type},body:bytes});const saved=await res.json();if(saved.sha256!==sha||saved.bytes!==row.file.size)throw new Error('Файл не подтверждён сервером');
   frames.push({id:'step_'+row.step,step:row.step,yaw:row.yaw,file:row.source.file,imageKey:saved.key,sha256:sha,bytes:saved.bytes,stamp_ns:row.source.stamp_ns??null,measured_pose:row.source.measured_pose??null,waypoint:row.source.waypoint??null});
  }
  const capture=validateCapture({sceneId:task.id,sessionId:metadata.sessionId??('take_'+crypto.randomUUID()),mode:task.mode??'shelf',skuId:task.sku_id??null,classId:task.class_id??null,className:task.class_name??null,skuOrder:task.sku_order??[],yaw:task.yaw_deg??null,purpose:task.purpose??'halfsynth',operator:metadata.operator??'',camera:metadata.image_topic??metadata.camera??'Не указан',settingsVersion:metadata.settingsVersion??'plan-v1',recordedAt:metadata.recordedAt??new Date().toISOString(),complete:metadata.status==='complete',frames},task);
  this.sync.edit(task.id,{capture:JSON.stringify(capture),review:'',session:capture.sessionId});await this.sync.sync();if(this.sync.pending[task.id+':capture']||this.sync.conflicts[task.id+':capture'])throw new Error('Результат пока не подтверждён базой. Повторите синхронизацию.');this.sync.edit(task.id,{status:capture.complete?'captured':'needs_review'});await this.sync.sync();this.toast(capture.complete?'Файлы записаны — можно проверять':'Сохранён неполный результат');
 }
 async importFolder(files){const task=this.task,manifestFile=files.find(f=>['episode.json','capture.json'].includes(f.name));if(!manifestFile)throw new Error('Нужен episode.json или capture.json рядом с папкой images');const manifest=JSON.parse(await manifestFile.text()),base=manifestFile.webkitRelativePath.split('/').slice(0,-1).join('/');const mapped=files.map(f=>({file:f,relative:f.webkitRelativePath.slice(base.length+1)}));const rows=buildFolderCapture(task,manifest,mapped);await this.upload(task,rows,manifest);}
 async exportFrames(){const c=parse(this.getRecord(this.task.id).capture);if(!c.frames?.length)throw new Error('Нет кадров');const entries=[],frames=[];for(const f of c.frames){const response=await this.sync.api('/api/image?key='+encodeURIComponent(f.imageKey)),data=new Uint8Array(await response.arrayBuffer()),sha=[...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(x=>x.toString(16).padStart(2,'0')).join('');if(sha!==f.sha256)throw new Error('Хэш оригинала не совпал');const name='images/'+String(f.step).padStart(2,'0')+'_'+f.id+(f.imageKey.endsWith('.png')?'.png':'.jpg');entries.push({name,data});frames.push({...f,file:name});}const record=this.getRecord(this.task.id);entries.push({name:'capture.json',data:JSON.stringify({...c,status:c.complete?'complete':'incomplete',frames,review:parse(record.review),reviewStatus:record.status},null,2)});const url=URL.createObjectURL(zipFiles(entries)),link=document.createElement('a');link.href=url;link.download=this.task.id+'_'+c.sessionId+'.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.toast('Скачаны только актуальные версии кадров');}
 async history(){const res=await this.sync.api('/api/history?scene='+encodeURIComponent(this.task.id));const data=await res.json();$('history-list').innerHTML=data.sessions.map((v,i)=>{const c=parse(v.value);return `<button class="history-item" data-history-index="${i}"><b>${esc(c.sessionId??'Сессия')}</b><span>${c.frames?.length??0} кадров · ${esc(v.updated_at)}</span></button>`;}).join('')||'<p>Пересъёмок ещё нет</p>';$('history-dialog').showModal();for(const b of $('history-list').querySelectorAll('[data-history-index]'))b.onclick=()=>{this.historyCapture=parse(data.sessions[Number(b.dataset.historyIndex)].value);this.reviewTask=this.task;this.index=0;$('history-dialog').close();$('review-dialog').showModal();this.renderReview();};}
 async agentFetch(path,options={}){if(!this.agent)throw new Error('Подключите компьютер сбора');const res=await fetch(this.agent.url+path,{...options,headers:{Authorization:'Bearer '+this.agent.token,...options.headers},signal:AbortSignal.timeout(10000)});if(!res.ok){const d=await res.json();throw new Error(d.error??'Компьютер сбора не отвечает');}return res;}
 async connectAgent(){const url=new URL($('agent-url').value);if(!['127.0.0.1','localhost'].includes(url.hostname)||url.protocol!=='http:')throw new Error('Используйте локальное подключение http://127.0.0.1:8935');this.agent={url:url.origin,token:$('agent-token').value.trim()};try{const res=await this.agentFetch('/local/state');this.agentState=await res.json();$('agent-error').textContent='';this.renderAgent();}catch(e){this.agent=null;throw e;}}
 async agentCommand(path,body){const res=await this.agentFetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});this.agentState=await res.json();this.renderAgent();}
 async pollAgent(){if(!this.agent||!$('agent-dialog').open||this.polling)return;this.polling=true;try{this.agentState=await (await this.agentFetch('/local/state')).json();this.renderAgent();if(this.agentState.cameraFresh){const blob=await (await this.agentFetch('/local/preview')).blob();if(this.previewUrl)URL.revokeObjectURL(this.previewUrl);this.previewUrl=URL.createObjectURL(blob);$('live-preview').src=this.previewUrl;}}catch(e){$('agent-error').textContent=e.message;this.agentState=null;this.renderAgent();}finally{this.polling=false;}}
 renderAgent(){const s=this.agentState;$('agent-state').textContent=s?.message??'Компьютер сбора не подключён';$('agent-progress').textContent=s?`${s.saved??0}/${s.expected??0} · ${s.sessionId??''}`:'';$('agent-instruction').textContent=s?.instruction??'Запустите локальный сервис рядом с камерой. Публичный сайт не подключается к роботу самостоятельно.';$('agent-controls').querySelectorAll('button').forEach(b=>{const a=b.dataset.capture;b.disabled=!s||(a==='agent-start'&&s.active)||(a==='agent-save'&&!s.canSave)||(a==='agent-import'&&!s.saved)||(a==='agent-reshoot'&&(!s.saved||s.active||s.mode!=='isolated'));});$('agent-step').max=s?.expected??12;}
 async importAgent(){const res=await this.agentFetch('/local/result');const m=await res.json();if(m.sceneId!==this.task.id)throw new Error('На компьютере записано другое задание');const rows=[];for(const f of m.frames){const fileRes=await this.agentFetch('/local/file?file='+encodeURIComponent(f.file));const file=new File([await fileRes.blob()],f.file.split('/').at(-1),{type:'image/png'});rows.push({file,source:f,step:f.step,yaw:f.yaw});}await this.upload(this.task,rows,m);}
}
