export const API_BASE=(typeof location!=='undefined'&&['localhost','127.0.0.1'].includes(location.hostname))?location.origin:'https://yolo-sku-lab-34-1010.epic-luck-9701.chatgpt.site';
export const DEFAULTS={status:'planned',note:'',session:'',capture:'',review:'',problem:'',operator:''};
export const LIMITS={status:30,note:4000,session:120,capture:120000,review:20000,problem:6000,operator:100};
export class JournalSync {
 constructor({storage,fetcher=(...args)=>fetch(...args),apiBase=API_BASE,validIds,onChange=()=>{},legacy={}}){
  Object.assign(this,{storage,fetcher,apiBase,validIds,onChange,legacy});this.fields={};this.pending={};this.conflicts={};this.connected=false;this.running=false;this.message='Подключите общий журнал';this.storageOk=true;
  try{this.token=storage.getItem('yolo-team-code')??'';const cache=JSON.parse(storage.getItem('yolo-shared-journal-v1')??'{}');for(const v of Object.values(cache.fields??{}))if(this.validRow(v))this.fields[this.key(v.scene_id,v.field)]=v;for(const p of Object.values(cache.pending??{}))if(this.validRow({...p,version:p.expected_version})&&typeof p.baseValue==='string')this.pending[this.key(p.scene_id,p.field)]=p;}catch{this.storageOk=false;this.token='';}
 }
 key(id,field){return id+':'+field;}
 validRow(v){return v&&this.validIds.has(v.scene_id)&&Object.hasOwn(LIMITS,v.field)&&typeof v.value==='string'&&v.value.length<=LIMITS[v.field]&&Number.isSafeInteger(v.version)&&v.version>=0;}
 row(id,field){return this.fields[this.key(id,field)]??{scene_id:id,field,value:DEFAULTS[field],version:0,updated_at:null};}
 records(){const out={};for(const id of this.validIds){const r={...DEFAULTS,updatedAt:null};let present=false;for(const f of Object.keys(DEFAULTS)){const row=this.row(id,f),p=this.pending[this.key(id,f)];if(row.version||p)present=true;r[f]=p?.value??row.value;const t=p?.queuedAt??row.updated_at;if(t&&(!r.updatedAt||t>r.updatedAt))r.updatedAt=t;}if(present)out[id]=r;}return out;}
 persist(){try{this.storage.setItem('yolo-shared-journal-v1',JSON.stringify({fields:this.fields,pending:this.pending}));this.storageOk=true;}catch{this.storageOk=false;}this.onChange(this);}
 label(){if(!this.storageOk)return 'Кэш недоступен · скачайте копию';if(Object.keys(this.conflicts).length)return 'Конфликт · выберите версию';const n=Object.keys(this.pending).length;return this.connected?(n?`Отправляем: ${n}`:'Синхронизировано'):(n?`На устройстве: ${n} · ждём связи`:this.message);}
 async api(path,options={}){const res=await this.fetcher(this.apiBase+path,{...options,headers:{Authorization:'Bearer '+this.token,...options.headers},signal:AbortSignal.timeout(20000),cache:'no-store'});if(!res.ok&&res.status!==409){let d;try{d=await res.json();}catch{}const e=new Error(d?.error??'Сервер недоступен');e.status=res.status;throw e;}return res;}
 async request(method,body){const res=await this.api('/api/journal',{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});return {status:res.status,data:await res.json()};}
 accept(row){if(!this.validRow(row))return;const k=this.key(row.scene_id,row.field),p=this.pending[k];this.fields[k]=row;if(p){if(row.value===p.value){delete this.pending[k];delete this.conflicts[k];}else if(row.version!==p.expected_version){if(row.value===p.baseValue){p.expected_version=row.version;delete this.conflicts[k];}else this.conflicts[k]={...row};}}}
 edit(id,change){for(const [field,value]of Object.entries(change)){if(!Object.hasOwn(LIMITS,field))continue;const row=this.row(id,field),k=this.key(id,field),old=this.pending[k];if(!this.validRow({...row,value}))continue;if(value===row.value&&!this.sending){delete this.pending[k];delete this.conflicts[k];continue;}this.pending[k]={scene_id:id,field,value,expected_version:old?.expected_version??row.version,baseValue:old?.baseValue??row.value,mutation_id:crypto.randomUUID(),queuedAt:new Date().toISOString()};}this.persist();clearTimeout(this.timer);this.timer=setTimeout(()=>this.sync(),650);}
 async connect(token){this.token=token.trim();const result=await this.request('GET');this.connected=true;this.fields={};for(const row of result.data.fields)this.accept(row);this.storage.setItem('yolo-team-code',this.token);
  for(const [id,r]of Object.entries(this.legacy)){if(!this.validIds.has(id))continue;for(const field of ['note','session']){const value=r[field]??'',row=this.row(id,field),k=this.key(id,field);if(!value||this.pending[k]||value===row.value)continue;this.pending[k]={scene_id:id,field,value,expected_version:0,baseValue:'',mutation_id:crypto.randomUUID(),queuedAt:r.updatedAt??new Date().toISOString()};if(row.version)this.conflicts[k]=row;}if(r.status==='done'&&!this.row(id,'capture').version)this.edit(id,{note:(r.note?r.note+'\n':'')+'Прежняя отметка «Снято»: требуется подтвердить файлы.'});}
  this.legacy={};this.persist();await this.sync();
 }
 async sync(){if(this.running||!this.token)return;this.running=true;try{const snapshot=await this.request('GET');for(const row of snapshot.data.fields)this.accept(row);this.connected=true;
  for(const [k,queued]of Object.entries(this.pending)){if(this.conflicts[k])continue;const p={...queued};this.sending=true;const result=await this.request('POST',p);this.sending=false;const row=result.data.field;if(result.status===200){this.fields[k]=row;const current=this.pending[k];if(current?.mutation_id===p.mutation_id){delete this.pending[k];delete this.conflicts[k];}else if(current){current.expected_version=row.version;current.baseValue=row.value;}}else this.accept(row);this.persist();}this.message='Синхронизировано';
 }catch(e){this.connected=false;this.message=e.status===401?'Введите код команды':'Нет связи · изменения на устройстве';}finally{this.sending=false;this.running=false;this.persist();}}
 resolve(k,useLocal){if(!this.conflicts[k])return;const row=this.fields[k];if(useLocal){const p=this.pending[k];p.expected_version=row.version;p.baseValue=row.value;p.mutation_id=crypto.randomUUID();}else delete this.pending[k];delete this.conflicts[k];this.persist();this.sync();}
 disconnect(){this.token='';this.connected=false;this.message='Подключите общий журнал';this.storage.removeItem('yolo-team-code');this.persist();}
}
